export const projectsData = [

  {
  id: 1,
  src: "/images/projects/work1.jpg",
  category: "Video Production",
  title: "Promotional Video Production",
  video: "https://drive.google.com/file/d/1ISEUyEN8rzB4IeNA3-wCPAcpiEn-G7EI/preview",
},
  {
    id: 2,
    src: "/images/projects/work2.jpg",
    category: "Video Production",
    title: "Social Media Video Editing",
    video: "https://drive.google.com/file/d/1gRuw0jo3__ulsnhji1MNDwC0J52Bo_tA/preview",   },
  {
    id: 3,
    src: "/images/projects/work3.jpg",
    category: "Video Production",
    title: "Event Videography Highlights",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 4,
    src: "/images/projects/work4.jpg",
    category: "Video Production",
    title: "YouTube Video Editing Project",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 5,
    src: "/images/projects/work1.jpg",
    category: "Video Production",
    title: "Instagram Reel Editing",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 6,
    src: "/images/projects/work2.jpg",
    category: "Video Production",
    title: "Corporate Promo Video",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 7,
    src: "/images/projects/work3.jpg",
    category: "Video Production",
    title: "Travel Cinematic Video",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 8,
    src: "/images/projects/work4.jpg",
    category: "Video Production",
    title: "Product Advertisement Video",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 9,
    src: "/images/projects/work1.jpg",
    category: "Video Production",
    title: "Short-form Content Editing",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },
  {
    id: 10,
    src: "/images/projects/work2.jpg",
    category: "Video Production",
    title: "Creative Storytelling Video",
    link: "https://drive.google.com/drive/folders/1dnpeDyWmlK9WKA5QLSpkkD6K8aGNGscv",
  },

  {
    id: 11,
    src: "/images/projects/Work5.jpg",
    category: "Photography",
    title: "Creative Photography Project",
  },

  {
    id: 12,
    src: "/images/projects/work6.jpg",
    category: "Poster Design",
    title: "Event Promotional Poster",
  },
  {
    id: 13,
    src: "/images/projects/work6.jpg",
    category: "Poster Design",
    title: "Social Media Marketing Poster",
  },

  {
  id: 14,
  src: "/images/thumbnails/NIHAL.jpeg",
  category: "Thumbnails",
  title: "Lifestyle Vlog Thumbnail – Nihal Hameed",
  link: "https://www.youtube.com/@Nihalkkaaaa",
},
{
  id: 15,
  src: "/images/thumbnails/IMG_5704.JPG.jpeg",
  category: "Thumbnails",
  title: "Lifestyle Vlog Thumbnail - Supervaava",
  link: "https://www.youtube.com/@Supervaava",
},
{
  id: 16,
  src: "/images/thumbnails/15.jpg",
  category: "Thumbnails",
  title: "Travel & Adventure Vlog Thumbnail - Backpacker Arunima",
  link: "https://www.youtube.com/@backpackerarunima2466",
},
{
  id: 17,
  src: "/images/thumbnails/Artboard 12.jpg",
  category: "Thumbnails",
  title: "Family Lifestyle Vlog Thumbnail - Basil Vlogs",
  link: "https://www.youtube.com/@basilvlogss",
},
{
  id: 18,
  src: "/images/thumbnails/Artboard 52.jpg",
  category: "Thumbnails",
  title: "Lifestyle Travel Thumbnail - Nabeel Ahammed K",
  link: "https://www.youtube.com/@nabeel_ahammed.k",
},
{
  id: 19,
  src: "/images/thumbnails/Artboard 55.jpg",
  category: "Thumbnails",
  title: "Lifestyle Travel Vlog Thumbnail - Arxhu Vlogs",
  link: "https://www.youtube.com/@arxhuvlogs",
},
 
]